server:
  port: 8000

spring:
  datasource:
    username: shiwarai
    password: shiwarai
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smart_dormitory
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect